# Generated by Django 5.2 on 2026-04-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
